version: '3'

services:
  drupal:
    image: drupal:10-apache
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - drupal_network

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    restart: always
    networks:
      - drupal_network
networks:
  drupal_network:
    driver: bridge
